services:
  home-assistant:
    container_name: homeassistant
    image: "ghcr.io/home-assistant/home-assistant:stable"
    volumes:
      - ./ha/config/:/config
      - /etc/localtime:/etc/localtime:ro
    devices:
      - /dev/ttyUSB0:/dev/ttyUSB0
      - /dev/ttyUSB1:/dev/ttyUSB1
    restart: unless-stopped
    privileged: true
    ports:
      - "8123:8123"
    networks:
      - ha-network


  plccoms:
    image: rosiste/plccoms
    restart: always
    ports:
      - "5010:5010"
    environment:
      - TZ=Europe/Prague
    volumes:
      - ./plc/log:/var/log/teco
      - ./plc/etc:/etc/teco
    networks:
      - ha-network

  mosquitto:
    image: eclipse-mosquitto
    restart: always
    environment:
      - TZ=Europe/Prague
    volumes:
        - ./mosquitto/config/:/mosquitto/config/
        - ./mosquitto/log/:/mosquitto/log/
        - ./mosquitto/data/:/mosquitto/data/
    ports:
      - "1883:1883"
      - "9001:9001"
    networks:
      - ha-network

  plccoms-mqtt-bridge:
    image: kub4/plccoms-mqtt-bridge:latest
    restart: always
    environment:
      - TZ=Europe/Prague
    volumes:
      - ./plccoms-mqtt-bridge/config.yaml:/etc/plccoms-mqtt-bridge/config.yaml
    networks:
      - ha-network

networks:
  ha-network:
    driver: bridge
